### ISSUE TITLE
VB not updating 

### ISSUE THREAD

**Issue by Veldian78** [GitHub-TC/EmpyrionBackpackExtender#1]
VB is not updating after player takes item(s) from the Virtual Backpack, I have looked and all code is in and the VB running fine with no errors but when a player adds something in, Then removes it after any length of time and then opens the VB again the items they removed are back in there and also copies in there normal bag, so it's essentially duplicating the items

**Comment by HawkieNorway** [comment]
Same issue here. This project seems abandoned. Duplicating issue happens with all backpacks

**Comment by GitHub-TC** [comment]
Mod works fine on my server in the bundle of ModLoader.zip package. No duplications or the like.
