### ISSUE TITLE
Items noch da aber keine Icons

### ISSUE THREAD

**Issue by dtmaster79** [GitHub-TC/EmpyrionBackpackExtender#10]
Hi,
ich habe mit der aktuellen Version des Mods aber auch schon mit der vorherigen Version das gleiche Problem.

Alle items sind noch im Backpack vorhanden, aber die sie sind nicht zu sehen. Erst wenn ich mit der Maus drüber gehe sind sie wieder sichtbar. Das Problem habe ich seit Version 1.7 von Empyrion raus kam.

Ich habe auf meinem Server als Szenario Reforged Eden 1.8 laufen.

Viele Grüße und danke für deine Arbeit.

**Comment by GitHub-TC** [comment]
Ist leider ein Fehler im Empyrion.
