### ISSUE TITLE
[Feature Request / Help] Regular Backpack slot increase?

### ISSUE THREAD

**Issue by volkb79** [GitHub-TC/EmpyrionBackpackExtender#11]
Hello,

probably the wrong place to ask, but this mod and author seems to be the best to get a good answer :)

I am just looking for a mod/config setting to increase the slot count in the personal backpack. E.g. quest items and other small stuff/quantities fill up slots, your backpack gets full even though there is lots of free volume left. 

A pointer to a existing solution or mod would be highly appreciated ;)

Kind regards,

**Comment by GitHub-TC** [comment]
The mask of the slots is hard coded by Eleon and unfortunately cannot be changed/extended by me.
