### ISSUE TITLE
Multi-Server application

### ISSUE THREAD

**Issue by Sandcrab2000** [GitHub-TC/EmpyrionBackpackExtender#15]
What changes and what files will need to be changed to allow multiple instances of the backpack extender to run on the same machine?

Running two servers on the same machine and I would like to have the BPE mod run on both servers simultaneously.

Currently, with both servers running, NEITHER server has the mod running.

**Comment by GitHub-TC** [comment]
Take a fresh installation of the ModLoader https://github.com/GitHub-TC/EmpyrionModPackage for each server or set the entries for the communication channels back to the initial value

EGS\Content\Mods\ModLoader\Client\Configuration.xml:
```
 <EmpyrionToModPipeName>EmpyrionToModPipe774795cf36144ecfa253eea882e75fe7x</EmpyrionToModPipeName>
 <ModToEmpyrionPipeName>ModToEmpyrionPipea08da4c068924612a55e5d6e5c305071x</ModToEmpyrionPipeName>
```
to
```
 <EmpyrionToModPipeName>EmpyrionToModPipe{0}</EmpyrionToModPipeName>
 <ModToEmpyrionPipeName>ModToEmpyrionPipe{0}</ModToEmpyrionPipeName>
```
