### ISSUE TITLE
Virtual Backback Extender

### ISSUE THREAD

**Issue by reserect** [GitHub-TC/EmpyrionBackpackExtender#6]
Okay so i have added the DLL's and such the \vb help works and such and it allows me to buy backpacks but they don't seem to open when attempting to open them can you verify if this is the case unless i am doing something wrong as stated i am able to bring up the help window so i know the mod is loading as should. using EWA to load it in.

**Comment by GitHub-TC** [comment]
Please use the latest https://github.com/GitHub-TC/EmpyrionModPackage ModLoader.zip package
