### ISSUE TITLE
Items Deleting

### ISSUE THREAD

**Issue by reserect** [GitHub-TC/EmpyrionBackpackExtender#7]
My players are adding items but finding out it is deleting them nothing has been added to the forbidden. reforged eden 1.7 backpacks are buyable but when things placed in then closed we open it again and nothing shows.

**Comment by reserect** [comment]
Okay so been 10 days and no responce i hope this is getting looked into.

**Comment by GitHub-TC** [comment]
Its a known bug in Empyrion
