### ISSUE TITLE
Not able to install

### ISSUE THREAD

**Issue by iceystreeeeet** [GitHub-TC/EmpyrionBackpackExtender#9]
I am using the EWA to install the mod but it will not let me and shows the following error

![image](https://user-images.githubusercontent.com/65880941/177023687-3a3241e4-0b7f-42f8-baea-cf17f3cd9610.png)

Any and all help is greatly appreciated

**Comment by GitHub-TC** [comment]
Upload the EmpyrionBackpackExtender.zip and not the source code

**Comment by bob-1234** [comment]
i am having this same issue. on your account page you have the EmpyrionBackpackExtender-Master.zip, when i try tp upload it using EWA i still get the error
if i try using the file in your empyrionModPackage it only has the dll and a config. 
any help you can provide would be appreciated!
